### ISSUE TITLE
librarian-puppet: Add procedure to update module

### ISSUE THREAD

**Issue by xironix** [bfirsh/loom#2]
Currently puppet.update executes "librarian-puppet install" which is useful if we add new modules. 

However, if we update the Puppetfile to bump version/reference numbers to use a later version, we'll want to run "librarian-puppet update" instead.

**Comment by bfirsh** [comment]
As far as I can see this is isn't a problem. If you specify a new version in Puppetfile and run `librarian-puppet update`, it updates it to the new module.

**Comment by xironix** [comment]
I'll have to check again, but I think this was an issue when I was switching between modules with the same name, but different sources.

I'll have to look more deeply at this, as it has been a while since I had to worry about such things.
