### ISSUE TITLE
Loom requires fabric before you can install.

### ISSUE THREAD

**Issue by sherzberg** [bfirsh/loom#22]
I think I broke the install of loom when I added the version number to loom/**init**.py. Is the from . import config required in loom/**init**.py? If not, removing it should fix this. If it is required, let me know and I can come up with something else.

**Comment by bfirsh** [comment]
Thanks – I don't think there's a decent solution to this. Celery actually parses **init**.py for example:

https://github.com/celery/celery/blob/master/setup.py
